PatterSearchJob: Use custom ForkJoinWorkerThreadFactory
eclipse-jdt/eclipse.jdt.core pull request #1017
Opened 2023-04-27 10:12 UTC by Christopher-Hermann

### What it does
In case a SecurityManager is installed, using the defaultForkJoinWorkerThreadFactory would result in worker threads with no permissions, which leads to not working java type search.

Use a custom ForkJoinWorkerThreadFactory implementation to work around this.

The same fix was also applied to org.eclipse.jdt.internal.core.JavaModelManager.java

See also:
https://github.com/eclipse-jdt/eclipse.jdt.core/pull/604
https://github.com/eclipse-platform/eclipse.platform/issues/294
https://github.com/eclipse-platform/eclipse.platform/pull/295

## How to test

1. Have any Eclipse-plugin that installs a SecurityManager. Use attached demo plugin [foo.bar.securitymanager.zip](https://github.com/eclipse-platform/eclipse.platform/files/10208024/foo.bar.securitymanager.zip) (Main Menu SecurityManager -> Install SecurityManager) or the following snippet:
Policy.getPolicy(); // init
Policy.setPolicy(new Policy() {
    @Override
    public boolean implies(ProtectionDomain domain, Permission permission) {
        return true;
    }
});
System.setSecurityManager(new SecurityManager());
2. Open ja Java project and open the type search (CTRL+SHIFT+T)
3. As soon as you start typing a error is shown

## Author checklist

- [X] I have thoroughly tested my changes
- [X] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [X] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

2023-04-27 15:21 UTC, Christopher-Hermann commented
Discussion in https://github.com/eclipse-platform/eclipse.platform.text/pull/185 will be relevant for this PR as well.

2023-04-30 09:42 UTC, gayanper approved these changes

2023-04-30 09:43 UTC, gayanper commented
Thanks @Christopher-Hermann, sorry for taking so long to approve. I was not well last week, slowly starting back.

2023-05-01 10:03 UTC, gayanper commented
@Christopher-Hermann seems like the build hangs. Could you investigate it ?

2023-05-03 14:16 UTC, iloveeclipse requested changes
Please undo the merge commit and rebase on master head instead

2023-05-04 08:37 UTC, Christopher-Hermann commented
> `commonPool` is never shutdown now & created on each job execution.

Done, thanks for the review.

2023-05-04 08:46 UTC, szarnekow commented
This is still creating a new pool for each index search. Putting aside that all stream().parallel() pipelines that are not initiated from within an existing parallel task or forkjoin task do still run on the common pool, I fail to see a systematic approach. It might make more sense to offer an equivalent to the common pool, e.g in one of the platform bundles as a primed pool that will be shutdown when the workspace / RCP is closed.

2023-05-08 06:51 UTC, closed without merging