[17] compiler.ast.CaseStatement.ResolvedCase.intValue not initialized for Strings #1126
eclipse-jdt/eclipse.jdt.core pull request #1128
Opened 2023-06-07 06:46 UTC by jarthana

## What it does
Fixed https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1126

## How to test

## Author checklist

- [x] I have thoroughly tested my changes
- [x] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [x] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

2023-06-13 07:05 UTC, jukzi commented on org.eclipse.jdt.core.tests.compiler/src/org/eclipse/jdt/core/tests/compiler/regression/SwitchPatternTest.java
> +					"	     case \"abc\" -> 0;\n"+
```suggestion
					"	     case \"FB\" -> 0;\n"+
```

2023-06-13 07:05 UTC, jukzi commented on org.eclipse.jdt.core.tests.compiler/src/org/eclipse/jdt/core/tests/compiler/regression/SwitchPatternTest.java
> +					"	     case \"abcd\" -> 1;\n"+
```suggestion
					"	     case \"Ea\" -> 1;\n"+
```

2023-06-13 07:07 UTC, jukzi requested changes

2023-06-13 07:07 UTC, jukzi commented on org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/internal/compiler/ast/SwitchStatement.java
> +										return c.intValue() == this.otherConstants[idx].intValue();
That shows an Error if two Strings have the same hashCode. For exampe "FB" and "Ea" gives "Duplicate case".

2023-06-13 07:56 UTC, jarthana commented
Yes, we have some failures due to the same reason. Will look into this.

2023-06-13 08:12 UTC, jarthana commented
So, it's not useful to do the int comparison. I thought of doing some optimization of falling back to String comparison when the int comparison returns true.  But I don't see much value as the Strings are probably compared for reference and interned as well. So, have to live with the fact that the intValue() is not much useful for String constants in case.

2023-06-13 08:17 UTC, jukzi commented
But did you try the test with hash-conflicting strings? it did still fail with revert for me.

2023-06-13 08:48 UTC, jarthana commented
> But did you try the test with hash-conflicting strings? it did still fail with revert for me.

Yes, now with us doing a simple String comparison, works fine. Will capture this in a new test case for the record.

2023-06-14 05:26 UTC, jarthana commented
> But did you try the test with hash-conflicting strings? it did still fail with revert for me.

@jukzi can you confirm that this no longer an issue?

2023-06-14 05:57 UTC, jukzi approved these changes
SwitchPatternTest now passes locally for me
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/51790620/296ff59c-2329-41d4-9aac-b1342193bbed)

2023-06-14 07:05 UTC, merged