fix "static field should be accessed in a static way"
eclipse-jdt/eclipse.jdt.core pull request #1160
Opened 2023-06-19 13:08 UTC by jukzi

reduce ecj warnings

2023-06-19 20:16 UTC, iloveeclipse requested changes

2023-06-19 20:16 UTC, iloveeclipse commented on org.eclipse.jdt.core.tests.model/src/org/eclipse/jdt/core/tests/model/AbstractJavaModelTests.java
> +		Hashtable defaultOptions = getDefaultJavaCoreOptions();
Please undo this change.

2023-06-19 20:20 UTC, jukzi commented on org.eclipse.jdt.core.tests.model/src/org/eclipse/jdt/core/tests/model/AbstractJavaModelTests.java
> +		Hashtable defaultOptions = getDefaultJavaCoreOptions();
upps. thanks for review!!

2023-06-20 05:18 UTC, iloveeclipse approved these changes

2023-06-20 05:18 UTC, merged