Use diamond operator in jdt.core
eclipse-jdt/eclipse.jdt.core pull request #1658
Opened 2023-11-30 16:39 UTC by vogella

Using the JDT UI clean-up, this removes the redundant type information in the jdt.core plug-in

## What it does

## How to test

## Author checklist

- [x] I have thoroughly tested my changes
- [x] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [x] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

2023-11-30 16:39 UTC, vogella commented
@jukzi WDYT?

2023-11-30 16:49 UTC, jukzi commented
> Shall the activation of this a error / warning do into this commit or another PR?

into this commit

2023-11-30 17:08 UTC, vogella commented
> > Why does JDT core not validate on all platform via its GH actions like platform and PDE? According to some test result pages which I have seen jdt tests are flunky on some platforms, e.g. https://download.eclipse.org/eclipse/downloads/drops4/I20231128-1800/testResults.php
> 
> i guess JDT depends more on java versions then on OS

I this case I would expect GH testing multiple Java versions.

2023-12-01 15:02 UTC, iloveeclipse commented
> I guess but I can send you a PR with 130 additional files + config changes

Please do it by bundle / not with ~100 files. We had enough regressions slipped through PR's with mass changes.

2023-12-01 15:02 UTC, jukzi commented
> Easier to review, I guess but I can send you a PR with 130 additional files + config changes

i think its better to have a single or very few PRs then for each plugin. 200 file is reviewable

2023-12-01 15:05 UTC, vogella commented
I'm getting different messages from @jukzi and @iloveeclipse

As @jukzi seems to be interested in actually reviewing, I followed his request. In case this leads @iloveeclipse to block, I can also split up by plug-in. With Git this only cost me a minute or so, so feel free to change your requirements.

2023-12-01 15:11 UTC, vogella commented
Give me a short while, while I review this here at GH myself, the compare editor in Eclipse is not so nice for reviewing such large changes (file by file comparison vrs all here at GH)

2023-12-01 15:15 UTC, jukzi commented
> Give me a short while, while I review this here at GH myself, the compare editor in Eclipse is not so nice for reviewing such large changes (file by file comparison vrs all here at GH)

GH so slow... sometimes i create a diff and review it with notepad instead :-)

2023-12-01 15:19 UTC, vogella commented
> > Give me a short while, while I review this here at GH myself, the compare editor in Eclipse is not so nice for reviewing such large changes (file by file comparison vrs all here at GH)
> 
> GH so slow... sometimes i create a diff and review it with notepad instead :-)

Sad that two Eclipse committer find the Eclipse IDE not good enough to compare (mass) changes.

2023-12-01 15:47 UTC, vogella commented
Change looks good to me, I was mainly scanning for lost comments, the JDT clean-ups are known to have bugs wrt. comments.

Glad to see that no version change seems necessary, I guess I have to thank @HannesWell StringBuffer change for that.

2023-12-01 15:54 UTC, vogella commented
> Give me a short while, while I review this here at GH myself, the compare editor in Eclipse is not so nice for reviewing such large changes (file by file comparison vrs all here at GH)

Ready for a review by @jukzi

2023-12-01 16:38 UTC, vogella commented on org.eclipse.jdt.annotation/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.problem.redundantSpecificationOfTypeArguments=error
Done

2023-12-01 16:38 UTC, vogella commented on .gitignore
> +# pomless
Removed

2023-12-01 16:50 UTC, jukzi requested changes
A single option seems wrong, everything else straight forward. have a nice weekend

2023-12-01 16:50 UTC, jukzi commented on org.eclipse.jdt.apt.pluggable.tests/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.problem.uncheckedTypeOperation=info
unrelated change?

2023-12-01 16:50 UTC, jukzi commented on org.eclipse.jdt.core/model/org/eclipse/jdt/internal/core/util/WeakHashSet.java
> +		WeakHashSet<T> newHashSet = new WeakHashSet<>(this.elementSize * 2);		// double the number of expected elements
intersting: my own code modernized :-)

2023-12-01 16:53 UTC, vogella commented on org.eclipse.jdt.apt.pluggable.tests/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.problem.uncheckedTypeOperation=info
Undone the unrelated change

2023-12-04 08:02 UTC, merged