Sort filename (if given) by name for consistent output
eclipse-jdt/eclipse.jdt.core pull request #1922
Opened 2024-01-30 08:08 UTC by laeubi

Currently the generation of lamdas can change depending on when the source file is processed.

## What it does

This sorts the array of files (if given) to always have a predictable order independent of order given on the commandline / arguments.

Relates to https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1921

## How to test
Use this project:
- https://github.com/eclipse-pde/eclipse.pde/tree/master/ui/org.eclipse.pde.launching
- pass the source files in different order to the batch compiler
- see that depending on the order you get different lamda namings for the same code
- with this patch the ordering of source file arguments do not matter

See https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1921 for detailed compiler arguments, logs and example class files showing the difference.

## Author checklist

- [x] I have tested my changes in a debugger with a Tycho build by manipulating the passed source files order
- [x] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [x] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

2024-01-30 16:12 UTC, iloveeclipse requested changes
The problem is "per output destination" feature, see https://bugs.eclipse.org/bugs/show_bug.cgi?id=146554

`Main.filenames` & `Main.destinationPaths` should be in-sync, so change must be done not here but in `configure()`

2024-01-30 16:25 UTC, iloveeclipse commented
> I applied a workaround to Tycho to simulate what this patch does

I would keep that in Tycho, as the patch here is incomplete and needs to be fixed.

2024-01-31 07:05 UTC, laeubi commented
> The problem is "per output destination" feature, see https://bugs.eclipse.org/bugs/show_bug.cgi?id=146554
> 
> `Main.filenames` & `Main.destinationPaths` should be in-sync, so change must be done not here but in `configure()`

You are right, I also noticed that there are even `public fields` in this class so now I only sort the index here... another approach would be to do the ordering in the compiler itself I'll take a look at this as well.

2024-01-31 08:32 UTC, laeubi commented
This now seems to pass the testsuite and already shows some classes that are different in JDT, I have createad a PR here:
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1758

so get a better overview what would happen in the large (requires snapshot Tycho).

> I would keep that in Tycho, as the patch here is incomplete and needs to be fixed.

I leave the decisions to you (or JDT team) if this change is useful so it can benefit everyone not only latest Tycho users...

2024-01-31 08:36 UTC, iloveeclipse commented
> if this change is useful so it can benefit everyone not only latest Tycho users.

What I've meant is: as long as patch here is incomplete and breaks ecj functionality, Tycho workaround has to be used.
If the patch is OK, we will for sure like to have it in the compiler, as stable compilation behavior is important for everyone.

2024-01-31 08:40 UTC, laeubi commented
If I where to fix it on the compiler level it seems worth to sort the CUs by name in the method `org.eclipse.jdt.internal.compiler.Compiler.internalBeginToCompile(ICompilationUnit[], int)` I'll prepare a PR for this to see if it gives similar results but that's beyond my understanding if compiler internals to judge what is a better approach.

2024-01-31 08:50 UTC, laeubi commented
This is done on the Compiler /CU level
- https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1933

2024-01-31 10:47 UTC, merged

2024-01-31 15:56 UTC, laeubi commented
Looking at the build results this has not produced any baseline problem eve though it would be expected it seems the change has had not the same effect as desired...

2024-01-31 16:01 UTC, iloveeclipse commented
> Looking at the build results this has not produced any baseline problem eve though it would be expected it seems the change has had not the same effect as desired...

This change is needed to see new compiler used for SDK: https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1760