Fix VariableBinding.getJavaElement() type signature
eclipse-jdt/eclipse.jdt.core pull request #2037
Opened 2024-02-16 22:20 UTC by mickaelistria

Make signature format returned by the binding match the usual signature format for  IJavaElement.

Fixes https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2036

## How to test

Run provided unit test with/without fix to check fixes makes test pass.

## Author checklist

- [x] I have thoroughly tested my changes
- [x] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [x] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

2024-02-16 23:43 UTC, mickaelistria commented
The only test failure seems to be a recurring intermittent failure, not related to that patch: https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1094 . So it looks like this fixes 1 (new) test and doesn't cause any regression.

2024-03-06 20:15 UTC, mickaelistria commented
@rgrunber @jjohnstn Can you please review/merge this fix proposal?

2024-03-06 22:46 UTC, jjohnstn requested changes
Patch makes sense.  Since your logic treats arrays differently, you should add an array reference to your test.  Other than that, looks fine.

2024-03-07 07:41 UTC, mickaelistria commented
The test is already an array (`s1 = new Object[0]`). Am I missing something?

2024-03-07 15:42 UTC, jjohnstn commented
> The test is already an array (`s1 = new Object[0]`). Am I missing something?

Maybe I missed something.  In your test you have var s1 = args[0] so s1 is type Ljava.lang.String which you verify.  Line 271 of your patch does something extra if element is an array (e.g. var s2 = args).

2024-03-07 22:38 UTC, mickaelistria commented
I've added a check for arrays as suggested.

2024-03-08 05:17 UTC, jjohnstn commented
> I've added a check for arrays as suggested.

Thanks.  Check the test to see if the failure is due to misinterpreting what the result should be or whether it isn't doing what you expected.  When the test succeeds, I'll merge.

2024-03-08 06:24 UTC, mickaelistria commented
You were right wondering about those particular lines and asking for a test: adding the extra lines for arrays was a bug. I've removed them.

2024-03-08 16:42 UTC, jjohnstn approved these changes

2024-03-08 16:48 UTC, merged