Consider external paths in search scope
eclipse-jdt/eclipse.jdt.core pull request #227
Opened 2022-07-15 08:46 UTC by gerking

Change-Id: Ic4dc3213fb5c3c8c8fd213012a09eacd13dbe681
Signed-off-by: Christopher Gerking <christopher.gerking@kit.edu>

## What it does
Fixes #190

## How to test
Test project submitted to #190

## Author checklist

- [x] I have thoroughly tested my changes
- [x] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [x] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

2022-07-17 12:44 UTC, iloveeclipse commented
I see that you had an example with unit test on the issue. Could you please convert this unit test to "regular" JDT unit test that demonstrates the problem and helps to catch a possible regression later? There are few tests already existing, see subclasses of `org.eclipse.jdt.core.tests.model.AbstractJavaSearchTests`.

2022-07-28 06:39 UTC, gerking commented
> Could you please convert this unit test to "regular" JDT unit test that demonstrates the problem and helps to catch a possible regression later?

Easier said than done. Creating a JDT unit test was pretty easy, and it successfully demonstrates the fix during a local JUnit run. But when running the test with Surefire, the test project (that resides in the runtime workspace) cannot resolve its classpath. In particular, the `org.eclipse.pde.core.requiredPlugins` entry fails to resolve, so that required bundles such as `org.eclipse.jdt.annotation` cannot be found. But to demonstrate the problem, this bug needs a plug-in project with required bundles.

Can you provide any hints on how to make bundles such as JDT Annotations resolvable by a test project? Is PDE available during the Surefire runs? Is the amount of launched target bundles somehow restricted?

I hope that this is not the same problem discovered here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=578744

2022-08-17 14:31 UTC, gerking commented
> Is PDE available during the Surefire runs?

Obviously it was not, so I had to add PDE as a Surefire dependency to the `org.eclipse.jdt.core.tests.model` plugin. Commit 6ee074f. 

Another challenge was that the `simulateRestart()` routine of class `AbstractJavaModelTests` removes the listeners required by PDE (this is the same problem described by @stephan-herrmann in [bugzilla 314850](https://bugs.eclipse.org/bugs/show_bug.cgi?id=314850#c6). Thus if some test is running after another test triggered a workspace restart, PDE can't resolve the classpath of test projects anymore. Since PDE itself seems to provide no API to do a proper reset that would reestablish the required listeners (correct me if I'm wrong), I also had to modify the `AbstractJavaModelTests` to save/load those listeners before/after the workspace restart: Commit 4bc3718.

With these two additions, the test finally succeeds within Surefire. Interestingly the problem is not even reproducible with Surefire, so the test will always succeed regardless of whether the fix is present or not (false negative). But when exceuted with JUnit, the problem (and the fix) can be demonstrated reliably.

2023-02-11 14:24 UTC, gerking commented
> Could you please convert this unit test to "regular" JDT unit test that demonstrates the problem and helps to catch a possible regression later?

Done in commit 2c8a3b3. I finally managed to reproduce the bug without a PDE dependency. Accordingly, the problem is more general and occurs on external classpath containers in general. But interestingly, only those containers with a source attachment seem to be affected. Therefore my unit test reuses the TestContainer from `TestExternalLibContainerInitializer` and attaches a source path to it.

Fixed in commit 52ed5be by converting internal to external paths before checking the index.

2024-05-03 08:39 UTC, iloveeclipse commented
Looking into that, sorry I had more urgent issues to work on.
I see the last commit was a merge => I will rebase other two commits, squash & push now to see what the tests say on current master.

2024-05-03 09:58 UTC, iloveeclipse requested changes
I will push changes in a moment

2024-05-03 09:58 UTC, iloveeclipse commented on org.eclipse.jdt.core/search/org/eclipse/jdt/internal/core/search/JavaSearchScope.java
> +		currentContainerPath = convertInternalToExternalPath(currentContainerPath, fullPath);
I would avoid doing conversion on every container path in the loop during the `indexOf`, instead I would convert to the external paths immediately at creating the search containers and only convert once given path.
Same below.

2024-05-03 09:58 UTC, iloveeclipse commented on org.eclipse.jdt.core/search/org/eclipse/jdt/internal/core/search/JavaSearchScope.java
> +					return targetLocation.toString();
I believe we should use `toOSString()` here as that is what used in this class elsewhere for container paths

2024-05-03 12:17 UTC, iloveeclipse commented
With latest patch we see test fail below

```
junit.framework.ComparisonFailure: 
Unexpected search results.
----------- Expected ------------
ExternalType (not open) [in ExternalType.class [in p [in /home/jenkins/agent/workspace/eclipse.jdt.core-Github_PR-227/org.eclipse.jdt.core.tests.model/target/work/externalLib]]]
------------ but was ------------

---------------------- ----------
 expected:<[ExternalType (not open) [in ExternalType.class [in p [in /home/jenkins/agent/workspace/eclipse.jdt.core-Github_PR-227/org.eclipse.jdt.core.tests.model/target/work/externalLib]]]]> but was:<[]>
	at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertStringEquals(TestCase.java:267)
	at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertEquals(TestCase.java:242)
	at org.eclipse.jdt.core.tests.model.AbstractJavaModelTests.assertSearchResults(AbstractJavaModelTests.java:677)
	at org.eclipse.jdt.core.tests.model.AbstractJavaModelTests.assertSearchResults(AbstractJavaModelTests.java:663)
	at org.eclipse.jdt.core.tests.model.AbstractJavaModelTests.assertSearchResults(AbstractJavaModelTests.java:660)
	at org.eclipse.jdt.core.tests.model.JavaSearchTests.testExternalFolder2(JavaSearchTests.java:646)
```

The reason is that  `JavaSearchScope.packageFragmentRoot()` now uses **resolved** external paths to find matching `IPackageFragmentRoot` and that doesn't work. I will update PR.

2024-05-03 14:21 UTC, merged