AST DOM tests for EitherOrMultiPattern nodes
eclipse-jdt/eclipse.jdt.core pull request #2406
Opened 2024-05-02 03:43 UTC by subyssurendran666

## What it does

The PR contains the AST DOM tests of EitherOrMultiPattern nodes.
https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2087

## Author checklist

- [ ] I have thoroughly tested my changes
- [ ] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [ ] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

2024-05-02 05:04 UTC, mpalat requested changes

2024-05-02 05:04 UTC, mpalat commented on org.eclipse.jdt.core.tests.model/src/org/eclipse/jdt/core/tests/dom/ASTConverterEitherOrMultiPatternTest.java
> +		SwitchStatement switchDeclerationStatement = (SwitchStatement)blockStatements.get(1);
nitpicking: spelling :)

2024-05-02 05:04 UTC, mpalat commented on org.eclipse.jdt.core.tests.model/src/org/eclipse/jdt/core/tests/dom/ASTConverterEitherOrMultiPatternTest.java
> +					      case PushNotification _, EmailNotification _, SMSNotification(String _) when notification instanceof Object :
Good that record pattern also added.

2024-05-14 06:53 UTC, subyssurendran666 commented on org.eclipse.jdt.core.tests.model/src/org/eclipse/jdt/core/tests/dom/ASTConverterEitherOrMultiPatternTest.java
> +			this.currentProject.setOption(JavaCore.COMPILER_PB_ENABLE_PREVIEW_FEATURES, JavaCore.ENABLED);
JEP 456 is currently not a standard feature.

2024-05-14 06:53 UTC, subyssurendran666 commented on org.eclipse.jdt.core.tests.model/src/org/eclipse/jdt/core/tests/dom/ASTConverterEitherOrMultiPatternTest.java
> +					      case PushNotification _, EmailNotification _, SMSNotification(String _) when notification instanceof Object :
Done

2024-05-14 06:53 UTC, subyssurendran666 commented on org.eclipse.jdt.core.tests.model/src/org/eclipse/jdt/core/tests/dom/ASTConverterEitherOrMultiPatternTest.java
> +		SwitchStatement switchDeclerationStatement = (SwitchStatement)blockStatements.get(1);
Done. Corrected the spelling

2024-05-14 06:53 UTC, subyssurendran666 commented on org.eclipse.jdt.core.tests.model/src/org/eclipse/jdt/core/tests/dom/ASTConverterEitherOrMultiPatternTest.java
> +					      case PushNotification _, EmailNotification _, SMSNotification(String _) when notification instanceof Object :
Thanks

2024-05-17 05:45 UTC, subyssurendran666 commented on org.eclipse.jdt.core.tests.model/src/org/eclipse/jdt/core/tests/dom/ASTConverterEitherOrMultiPatternTest.java
> +		this.workingCopy = getWorkingCopy("/Converter_22/src/X.java", false/*resolve*/);
Done

2024-05-21 06:56 UTC, mpalat commented
@subyssurendran666 please synch with master in the light of https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2282

2024-07-16 07:43 UTC, closed without merging