re-introduced ClassFileReader.read(InputStream, String)
eclipse-jdt/eclipse.jdt.core pull request #2578
Opened 2024-06-17 10:12 UTC by LorenzoBettini

To avoid breaking Xtext.

The signature was changed in
https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2555

## What it does
This re-introduced `org.eclipse.jdt.internal.compiler.classfmt.ClassFileReader.read(InputStream, String)`, which was changed into `org.eclipse.jdt.internal.compiler.classfmt.ClassFileReader.read(byte[], String)` in https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2555, breaking Xtext (https://github.com/eclipse/xtext/issues/3089).

2024-06-17 10:36 UTC, jukzi commented on org.eclipse.jdt.core.tests.compiler/src/org/eclipse/jdt/core/tests/compiler/regression/XtextDependencies.java
> +	public void ClassFileReader_read_InputStream() throws FileNotFoundException, ClassFormatException, IOException {
you have to skip non-api FileNotFoundException

2024-06-17 10:36 UTC, jukzi commented on org.eclipse.jdt.core.tests.compiler/src/org/eclipse/jdt/core/tests/compiler/regression/XtextDependencies.java
> +		ClassFileReader.read(new FileInputStream("afile"), "afile");
Please clarify if you need FileInputStream or InputStream
```suggestion
		ClassFileReader.read((InputStream) null, (String) null);
```

2024-06-17 10:42 UTC, LorenzoBettini commented
@jukzi updated the PR according to your comments, thanks!

2024-06-17 10:42 UTC, jukzi commented
@iloveeclipse wdyt?

2024-06-17 10:52 UTC, jukzi commented on org.eclipse.jdt.core.tests.compiler/src/org/eclipse/jdt/core/tests/compiler/regression/XtextDependencies.java
> +		@SuppressWarnings("unused")
Maybe better return the result instead of assignment to avoid @SuppressWarnings("unused")? Sorry for back and forth.

2024-06-17 11:24 UTC, iloveeclipse requested changes
Please add `XtextDependencies.class` to `org.eclipse.jdt.core.tests.compiler.regression.TestAll.suite()`

The rest is OK IMO.

2024-06-18 06:07 UTC, LorenzoBettini commented
@jukzi @iloveeclipse updated the PR according to your comments

2024-06-18 06:07 UTC, jukzi approved these changes

2024-06-18 09:02 UTC, iloveeclipse approved these changes

2024-06-18 09:03 UTC, merged

2024-06-18 09:13 UTC, LorenzoBettini commented
Thank you!
I guess it will be available tomorrow in i-builds, right?