#Issue #565 - initial creation of intersection type
eclipse-jdt/eclipse.jdt.core pull request #2702
Opened 2024-07-10 19:16 UTC by kamilkrzywanski

## What it does
fixes issue #565 

## Author checklist

- [ ] I have thoroughly tested my changes
- [ ] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [ ] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

2024-07-24 10:18 UTC, kamilkrzywanski commented
@jarthana @mpalat Can you look at it?

2024-07-25 00:01 UTC, mpalat commented
> @jarthana @mpalat Can you look at it?

@jarthana - since it's APT will prefer you to have a look

2024-08-18 20:42 UTC, kamilkrzywanski commented
@jarthana can you review this change?

2024-08-19 09:42 UTC, jarthana requested changes
I find the code changes themselves acceptable. But the bundle versions are not required and tests need some changes.

2024-08-19 09:42 UTC, jarthana commented on org.eclipse.jdt.apt.pluggable.tests/src/org/eclipse/jdt/apt/pluggable/tests/processors/buildertester/Issue565Processor.java
> +		for (String classPath: classPathValues) {
Is this really required?

2024-08-19 09:42 UTC, jarthana commented on org.eclipse.jdt.apt.pluggable.tests/src/org/eclipse/jdt/apt/pluggable/tests/processors/buildertester/Issue565Processor.java
> +				if (element instanceof TypeElement) {
I am wondering we make the testing parameters a bit more elaborate? Looks like we aren't doing much with the visiting elements and all we check for is that getElementsAnnotatedWith() doesn't crash. We don't seem to be using what the keyBuilder is doing. Also, this for loop is not indented properly.

2024-08-19 09:42 UTC, jarthana commented on org.eclipse.jdt.apt.pluggable.tests/src/org/eclipse/jdt/apt/pluggable/tests/processors/buildertester/Issue565Processor.java
> +	private static boolean status = false;
I see the process() being executed twice. Perhaps you can check processingOver() like in other processors to filter out the last round.

2024-08-19 09:42 UTC, jarthana commented on org.eclipse.jdt.core.compiler.batch/pom.xml
> +  <version>3.39.100-SNAPSHOT</version>
This is not required as the minor version has already changed.

2024-08-19 09:42 UTC, jarthana commented on org.eclipse.jdt.core.compiler.batch/META-INF/MANIFEST.MF
> +Bundle-Version: 3.39.100.qualifier
This is not required as the minor version has already changed.

2024-08-19 09:42 UTC, jarthana commented on org.eclipse.jdt.core/META-INF/MANIFEST.MF
> +Bundle-Version: 3.39.100.qualifier
This is not required as the minor version has already changed.

2024-08-19 09:42 UTC, jarthana commented on org.eclipse.jdt.core/pom.xml
> +  <version>3.39.100-SNAPSHOT</version>
This is not required as the minor version has already changed.

2024-08-19 09:42 UTC, jarthana commented on org.eclipse.jdt.apt.pluggable.core/META-INF/MANIFEST.MF
> +Bundle-Version: 1.4.600.qualifier
This is not required as the minor version has already changed.

2024-08-19 09:42 UTC, jarthana commented on org.eclipse.jdt.apt.pluggable.tests/META-INF/MANIFEST.MF
> + org.eclipse.jdt.core;bundle-version="[3.39.0,4.0.0)",
This is not required as the minor version has already changed.

2024-08-19 16:36 UTC, kamilkrzywanski commented on org.eclipse.jdt.apt.pluggable.tests/src/org/eclipse/jdt/apt/pluggable/tests/processors/buildertester/Issue565Processor.java
> +		for (String classPath: classPathValues) {
My fault :) Removed

2024-08-20 05:47 UTC, jarthana commented on org.eclipse.jdt.apt.pluggable.tests/src/org/eclipse/jdt/apt/pluggable/tests/processors/buildertester/Issue565Processor.java
> +		for (Element element : roundEnv.getElementsAnnotatedWith(Annotation565.class)) {
This is causing a compilation problem. The previous change was better, imo. Also, please correct the indentation, squash all the changes if possible. And please mark all the resolved comments as such.

2024-08-20 05:53 UTC, jarthana approved these changes

2024-08-20 06:04 UTC, merged