Allow setting `name` of `RequiresDirective` to `null`
eclipse-jdt/eclipse.jdt.core pull request #3479
Opened 2024-12-18 22:40 UTC by datho7561

According to the child descriptor property, it's optional, so it makes sense that you should be able to set it to null. The Javadoc also doesn't mention anything about null not being allowed.

## What it does
- Don't throw an `InvalidArgumentException` when the name is set to null
- Don't lazily initialize the name

## How to test
- [ ] TODO: write some integration tests

## Author checklist

- [ ] I have thoroughly tested my changes
- [x] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [x] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

2025-01-02 18:09 UTC, datho7561 commented
@mpalat could you please review this code once you have a chance? From my understanding, you implemented `RequiresDirective`, so you probably have the best understanding of it. I don't understand why the name was being lazily initialized, and I don't understand why a qualified name was used in the lazy initalization.

2025-01-03 05:29 UTC, mpalat commented
> @mpalat could you please review this code once you have a chance? From my understanding, you implemented `RequiresDirective`, so you probably have the best understanding of it. I don't understand why the name was being lazily initialized, and I don't understand why a qualified name was used in the lazy initalization.

hmm.. well, let me scratch my old memory :)

Looking at the specs, I believe the name should have been MANDATORY rather than optional while it was modifiers that had to be optional - referring section - referring Section 7.7 of JLS :
requires {[RequiresModifier](https://docs.oracle.com/javase/specs/jls/se23/html/jls-7.html#jls-RequiresModifier)} [ModuleName](https://docs.oracle.com/javase/specs/jls/se23/html/jls-6.html#jls-ModuleName). So it's best to change the name to mandatory and leave lazy initialization in tact.

And to answer your second question on why a qualified name was used - I don't see why it should not be used. Guess that it so coded since this mimics import.  We can use either a Simple name or a QualifiedName since the ModuleName can be one of those - ref: [Section 6.5](https://docs.oracle.com/javase/specs/jls/se23/html/jls-6.html#jls-ModuleName). Am open for a change to SimpleName if it makes life easier in any case - but modules names tend to be qualified names mostly [no, I don;t have any statistics to prove that].

2025-01-03 05:30 UTC, mpalat requested changes
>@mpalat could you please review this code once you have a chance? From my understanding, you implemented RequiresDirective, so you probably have the best understanding of it. I don't understand why the name was being lazily initialized, and I don't understand why a qualified name was used in the lazy initalization.

hmm.. well, let me scratch my old memory :)

Looking at the specs, I believe the name should have been MANDATORY rather than optional while it was modifiers that had to be optional - referring section - referring Section 7.7 of JLS :
requires {[RequiresModifier](https://docs.oracle.com/javase/specs/jls/se23/html/jls-7.html#jls-RequiresModifier)} [ModuleName](https://docs.oracle.com/javase/specs/jls/se23/html/jls-6.html#jls-ModuleName). So it's best to change the name to mandatory and leave lazy initialization in tact.

And to answer your second question on why a qualified name was used - I don't see why it should not be used. Guess that it so coded since this mimics import. We can use either a Simple name or a QualifiedName since the ModuleName can be one of those - ref: [Section 6.5](https://docs.oracle.com/javase/specs/jls/se23/html/jls-6.html#jls-ModuleName). Am open for a change to SimpleName if it makes life easier in any case - but modules names tend to be qualified names mostly [no, I don;t have any statistics to prove that].

So I believe the name should be made mandatory and Javadoc updated rather than allowing null.

2025-01-03 14:11 UTC, datho7561 commented
Okay sounds good. I'll update this PR to mark the name as MANDATORY and update the Javadoc

2025-01-03 14:28 UTC, datho7561 commented
I've added a new commit that marks the name as MANDATORY and switches the default name over to a SimpleName. I'm going to wait for the CI results before removing the first commit

2025-01-03 16:10 UTC, datho7561 commented
Alright, it should be good to review: I've cleaned up the commit and added a test.

2025-01-06 06:47 UTC, mpalat requested changes
Thanks @datho7561 for the change. Only one more comment which I have tagged @jarthana for his take as well.

2025-01-06 06:47 UTC, mpalat commented on org.eclipse.jdt.core/dom/org/eclipse/jdt/core/dom/RequiresDirective.java
> +		new ChildPropertyDescriptor(RequiresDirective.class, "name", Name.class, MANDATORY, NO_CYCLE_RISK); //$NON-NLS-1$
@datho7561 Since this implies an API change, we should increment `@since`. It is indeed a grey area when we look at the API revision doc, but from a conservative point of view, I believe we should increment the version number. 
@jarthana - checking with you on your opinion.

2025-01-06 08:12 UTC, jarthana commented on org.eclipse.jdt.core/dom/org/eclipse/jdt/core/dom/RequiresDirective.java
> +		new ChildPropertyDescriptor(RequiresDirective.class, "name", Name.class, MANDATORY, NO_CYCLE_RISK); //$NON-NLS-1$
I am not sure about the @since version option. But two things worth noting:
1. No where in the Javadoc of the property do we mention about the option/mandatory aspect.
2. One of the usual clients, JDT/UI doesn't seem to be referencing this property at all, surprisingly.

So, we might get away with just "fixing" this bug, IMO.

2025-01-06 08:28 UTC, mpalat commented on org.eclipse.jdt.core/dom/org/eclipse/jdt/core/dom/RequiresDirective.java
> +		new ChildPropertyDescriptor(RequiresDirective.class, "name", Name.class, MANDATORY, NO_CYCLE_RISK); //$NON-NLS-1$
> So, we might get away with just "fixing" this bug, IMO.

@jarthana - thanks for chiming in.  you are right that this is not mentioned in the JavaDOC.
@datho7561 Let's take a call to go ahead and merge this change. +1

2025-01-06 08:28 UTC, mpalat approved these changes

2025-01-07 07:00 UTC, merged