[null] Assume instanceof local declaration non-null
eclipse-jdt/eclipse.jdt.core pull request #351
Opened 2022-08-29 12:45 UTC by mickaelistria

https://github.com/eclipse-jdt/eclipse.jdt.core/issues/350

## What it does

## How to test

## Author checklist

- [ ] I have thoroughly tested my changes
- [ ] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [ ] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

2022-08-29 12:48 UTC, mickaelistria commented
I can see an error locally, that I'm failing to understand, when this change is applied:
```
org.eclipse.jdt.core.tests.compiler.regression.NullAnnotationTests18#testNamedInstanceOfIsNonNull
[ERR]:Error: LinkageError occurred while loading main class X
	java.lang.ClassFormatError: Illegal field name " instanceOfPatternExpressionValue" in class X
```
I tried to debug it and I don't get how the change I wrote here actually affects the resulting AST in that way.
@stephan-herrmann any idea which trap caught me here?

2022-08-29 14:21 UTC, mickaelistria commented
Please ignore former comment, the issue was a configuration one on my end. Things should be good enough for review now.

2022-08-30 14:37 UTC, stephan-herrmann requested changes
I assume we are targeting 4.26, right? (I remember a time when bug reports had a defined target milestone ...)

The direction looks good. 

For a second I was pondering, whether we should instead tag the local with `TagBits.AnnotationNonNull`, but that would actually be wrong as witnessed by this variant of the test:
```
if (o instanceof String message) {
	consumeNonNull(message);
	message = null; // OK
	consumeNonNull(message); // NOK
}
```

If we'd fake a `@NonNull` on the variable, we'd get an error on "OK", but by using the flowInfo, we indeed get an error only at "NOK", which is correct.
Might be a good idea to add the above as a negative test.

2022-08-30 14:37 UTC, stephan-herrmann commented on org.eclipse.jdt.core.tests.compiler/src/org/eclipse/jdt/core/tests/compiler/regression/NullAnnotationTests18.java
> +				"		Object o = Math.random() > 0.5 ? new Object() : \"blah\";\n" +
Please don't create a test that may randomly fail. (yes, I saw it fail)

2022-08-30 14:37 UTC, stephan-herrmann commented on org.eclipse.jdt.core.tests.compiler/src/org/eclipse/jdt/core/tests/compiler/regression/NullAnnotationTests18.java
> +				"	}" +
in case we observe a compile error (which I did with an experimental variant of this test), missing \n makes it hard to match line numbers.

2022-08-30 15:10 UTC, mickaelistria commented
> I assume we are targeting 4.26, right?

Yes.

> (I remember a time when bug reports had a defined target milestone ...)

Only project committers can set the milestone on GitHub issues/PRs. So if you wish to add it, it would be welcome.

I'm working on implemented the improvements you suggest.

2022-08-30 17:03 UTC, stephan-herrmann commented
> Only project committers can set the milestone on GitHub issues/PRs. So if you wish to add it, it would be welcome.

last time I looked, no useful milestones were available, but I see this has been fixed for meanwhile.

2022-08-30 17:12 UTC, mickaelistria commented
I updated the patch as you suggested.

2022-08-30 17:57 UTC, stephan-herrmann commented on org.eclipse.jdt.core.tests.compiler/src/org/eclipse/jdt/core/tests/compiler/regression/NullAnnotationTests18.java
> +		//
nitpick: we normally prefer one test per test method, unless there's a very good excuse like reusing lots of test data.

2022-09-07 17:12 UTC, mickaelistria commented
@stephan-herrmann anything else you think must be improved?

2022-09-08 13:19 UTC, stephan-herrmann commented
> @stephan-herrmann anything else you think must be improved?

It's in my queue of things to look into now that master is re-opened.

A successful build would certainly help.

2022-09-08 14:40 UTC, mickaelistria commented
> A successful build would certainly help.

I'll rebase so we can see how things work or not, but I have the impression that the master branch isn't really in a stable state, so the build failure may be coming from a previous patch.

2022-09-13 15:40 UTC, stephan-herrmann commented on org.eclipse.jdt.core.tests.compiler/src/org/eclipse/jdt/core/tests/compiler/regression/NullAnnotationTests18.java
> +				"		Object o = Math.random() > 0.5 ? new Object() : \"blah\";\n" +
I still don't see the benefit of using Math.random() in tests, but at least id no longer causes harm.

2022-09-13 15:42 UTC, stephan-herrmann approved these changes

2022-09-13 16:56 UTC, merged

2022-09-13 16:56 UTC, stephan-herrmann commented
Thanks, @mickaelistria