Bug 574111 - Catch TheNotFoundPackage
eclipse-jdt/eclipse.jdt.core pull request #845
Opened 2023-03-16 11:57 UTC by guw

The condition must replicate what's possible in the outer condition on line 1126. The package is allowed to be null *and* TheNotFoundPackage.

Fixes https://github.com/eclipse-jdt/eclipse.jdt.core/issues/844

## What it does
Fixes #844.

## Author checklist

- [x] I have thoroughly tested my changes
- [x] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [x] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

2023-06-12 06:55 UTC, guw commented
@jarthana @stephan-herrmann I'd love to get this merged soon and not become stale again.

2023-06-14 11:31 UTC, iloveeclipse requested changes

2023-06-14 11:31 UTC, iloveeclipse commented on org.eclipse.jdt.apt.tests/src-ext/org/eclipse/jdt/apt/tests/external/annotations/batch/BatchGenProcessor.java
> +package org.eclipse.jdt.apt.tests.external.annotations.batch;
Please add license header

2023-06-16 02:05 UTC, jarthana commented
@guw The copyright header contains incorrect info. Please make it something like this - "Copyright (c) 2023 Salesforce and others". I tried to add a new commit myself on top of your change, but looks like you haven't enabled the permission to edit this PR.

2023-06-16 04:30 UTC, guw commented
@jarthana The tests are copied from other files in the project. Thus, the original header must be retained. I cannot claim a full copyright for the file.

2023-06-21 07:56 UTC, guw commented
@iloveeclipse @jarthana The failing test seems unrelated. Is it ok to ignore or should I disable the test?

2023-06-21 07:59 UTC, iloveeclipse commented
> @iloveeclipse @jarthana The failing test seems unrelated. Is it ok to ignore or should I disable the test?

That's one from https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1150 tests, should be fixed after rebase.

2023-06-21 07:59 UTC, iloveeclipse commented
@guw : looks like github is unable to rebase automatically, please rebase manually & push again.

2023-06-21 13:51 UTC, iloveeclipse approved these changes

2023-06-21 13:51 UTC, merged

2023-06-21 13:52 UTC, iloveeclipse commented
@guw : thanks for your contribution / patience with PR.