Error marker when null analysis enabled
eclipse-jdt/eclipse.jdt.core pull request #855
Opened 2023-03-17 16:25 UTC by snjeza

Fixes #854

2023-03-17 17:37 UTC, snjeza commented
@iloveeclipse It is similar to #629

2023-03-17 17:42 UTC, iloveeclipse commented
> @iloveeclipse It is similar to #629

Thanks, but I really mean that a commit message should provide all essential information required to understand the change. It is later the only place where one can see explanation for a typical question "why on hell this line is doing this"?

2023-03-17 17:50 UTC, snjeza commented
@iloveeclipse I have updated the PR.

2023-03-21 18:47 UTC, gayanper commented
@snjeza You are providing lot of fixes to JDT, and sometimes its seems wasteful to repeat whats already there. But it usefull when we have a commit message which summaries the fix, specially if you are looking at git log from editor, cli or IDE which may or may not have github support.

I think what @iloveeclipse try describe is to follow this https://github.com/eclipse-jdt/eclipse.jdt.core/wiki/FAQ-JDT-Core-Committer#committing-and-creating-a-pr-for-review when you make the commit message. You can copy the same to the PR message a well. Personally even my self I fail time to time keep up with the format. But a quick look at the PR stack I can see https://github.com/eclipse-jdt/eclipse.jdt.core/pull/866/commits which follows the expected convention.

2023-03-21 19:06 UTC, snjeza commented
@gayanper @iloveeclipse I have updated the PR - https://github.com/eclipse-jdt/eclipse.jdt.core/pull/855/commits/2dfa574065420b8f4c3838da906acb0c9787535b

2023-03-23 15:19 UTC, stephan-herrmann requested changes
I'm slightly worried about each of these tweaks affecting the order of resolution, but for lack of a strategy to avoid this (I'll think more about that later), I think the direction of this change is OK.

2023-03-23 23:56 UTC, snjeza commented on org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/internal/compiler/lookup/ReferenceBinding.java
> +						&& sourceType.scope.compilerOptions().isAnnotationBasedNullAnalysisEnabled) {
It has been fixed.

2023-03-23 23:57 UTC, snjeza commented on org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/internal/compiler/lookup/ReferenceBinding.java
> +							if (binding.isCompatibleWith(otherReferenceType)) {
It has been fixed.

2023-03-23 23:58 UTC, snjeza commented
@stephan-herrmann @iloveeclipse @gayanper I have updated the PR.

2023-03-23 23:58 UTC, snjeza commented on org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/internal/compiler/lookup/ReferenceBinding.java
> +					TypeReference reference = sourceType.scope.referenceContext.superclass;
It has been fixed within https://github.com/eclipse-jdt/eclipse.jdt.core/issues/629

2023-04-02 17:58 UTC, stephan-herrmann commented on org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/internal/compiler/lookup/ReferenceBinding.java
> +					TypeReference reference = sourceType.scope.referenceContext.superclass;
> It has been fixed within #629

I don't understand the connection. What has been fixed in #629 that affects `ReferenceBinding.isCompatible0()`?

2023-04-02 18:21 UTC, snjeza commented on org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/internal/compiler/lookup/ReferenceBinding.java
> +					TypeReference reference = sourceType.scope.referenceContext.superclass;
#629 fixes a similar issue related to `superInterfaces`. Please see
- https://github.com/snjeza/eclipse.jdt.core/blob/master/org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/internal/compiler/lookup/ReferenceBinding.java#L1353
- https://github.com/snjeza/eclipse.jdt.core/blob/master/org.eclipse.jdt.core.tests.compiler/src/org/eclipse/jdt/core/tests/compiler/regression/NullAnnotationTests18.java#L632
- https://github.com/snjeza/eclipse.jdt.core/blob/master/org.eclipse.jdt.core.tests.compiler/src/org/eclipse/jdt/core/tests/compiler/regression/NullAnnotationTests18.java#L661
-

2023-05-16 23:38 UTC, snjeza commented
The issue has been fixed via https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1067

2023-05-16 23:38 UTC, closed without merging

2023-05-23 20:18 UTC, stephan-herrmann commented
> The issue has been fixed via https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1067

After a 180 degree turn the issue will be fixed via #1077 instead of ~~#1067.~~

I'm sorry I couldn't give more substance to my vague worries up-front, which might have avoided some detours ...